env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  no-unsafe-finally: 0
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
